name: puppeteer tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test-puppeteer:
    name: puppeteer tests
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: volta-cli/action@v4

      - name: npm install
        run: npm install --frozen-lockfile

      - name: build
        run: npm run build

      - name: test - puppeteer
        run: npm run test:puppeteer
